metadata-version = "2015-12-19"
log-level = "debug"
onetime = false
interval = 60

[[ template ]]
source = "/etc/rancher-conf/metricbeat.yml.tmpl"
dest = "/etc/rancher-conf/metricbeat/metricbeat.yml"
notify-cmd = "sh /etc/rancher-conf/setup.sh"
notify-out = true
